import pygame

VERSION = 'X.Y'
# SCREEN_WIDTH = 720
# SCREEN_HEIGHT = 480
SCREEN_WIDTH = 1440
SCREEN_HEIGHT = 960

BUTTON_WIDTH = int(SCREEN_WIDTH * 0.625 // 3)  # important
BUTTON_HEIGHT = int(SCREEN_HEIGHT * 5 // 81)


TOGGLE_WIDTH = int(BUTTON_WIDTH * 0.875)
TOGGLE_ADJ = int(BUTTON_WIDTH * 0.075)
SCORE_ANCHOR = SCREEN_WIDTH - 8, -5
# MENU_TEXT = pygame.font.Font(FONT_LIGHT, int(110 / 1080 * SCREEN_HEIGHT))
# LARGE_TEXT = pygame.font.Font(FONT_REG, int(40 / 1080 * SCREEN_HEIGHT))
# MEDIUM_TEXT = pygame.font.Font(FONT_LIGHT, int(35 / 1440 * SCREEN_HEIGHT))
# SMALL_TEXT = pygame.font.Font(FONT_BOLD, int(25 / 1440 * SCREEN_HEIGHT))
# HUD_TEXT = pygame.font.Font(FONT_REG, int(40 / 1440 * SCREEN_HEIGHT))